name: Allure Report

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Instalar dependencias
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install

      # 4. Ejecutar tests y generar resultados Allure
      - name: Run tests
        run: |
          python -m pytest --alluredir=allure-results

      # 5. Instalar Allure CLI (forma moderna)
      - name: Install Allure CLI
        run: npm install -g allure-commandline --save-dev

      # 6. Generar reporte HTML
      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o allure-report

      # 7. Publicar en GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report